use serde::Deserialize;
use std::{collections::HashMap, fs};

/// Data as extracted from statistics files generated by analyze.sh.
pub struct Data {
    pub core: HashMap<String, TokeiCodeStatistics>,
    pub devtools: HashMap<String, TokeiCodeStatistics>,
    pub sdks: HashMap<String, TokeiCodeStatistics>,
    pub thirdparty: HashMap<String, TokeiCodeStatistics>,
    pub userspace: HashMap<String, TokeiCodeStatistics>,
    // TODO: userspace
}

impl Data {
    pub fn load(stats_path: &str) -> Self {
        Data {
            core: Self::load_file(format!("{stats_path}core.json")),
            devtools: Self::load_file(format!("{stats_path}devtools.json")),
            sdks: Self::load_file(format!("{stats_path}sdks.json")),
            thirdparty: Self::load_file(format!("{stats_path}thirdparty.json")),
            userspace: Self::load_file(format!("{stats_path}userspace.json")),
        }
    }

    fn load_file(p: String) -> HashMap<String, TokeiCodeStatistics> {
        println!("{p}");
        let content = fs::read_to_string(&p).unwrap();
        serde_json::from_str(content.as_str()).unwrap()
    }
}
// FIXME: put files with test in file name seperate

#[derive(Debug, Deserialize)]
pub struct TokeiCodeStatistics {
    pub children: Option<HashMap<String, Vec<TokeiReport>>>,
    pub blanks: u32,
    pub code: u32,
    pub comments: u32,
    //pub inaccurate: Option<bool>,
    pub reports: Option<Vec<TokeiReport>>,
}

#[derive(Debug, Deserialize)]
pub struct TokeiReport {
    pub name: String,
    pub stats: TokeiStats,
}

#[derive(Debug, Deserialize)]
pub struct TokeiStats {
    pub blanks: u32,
    pub code: u32,
    pub comments: u32,
    pub blobs: HashMap<String, TokeiCodeStatistics>,
}
